name: Deploy Backend

on:
  push:
    branches:
      - main  # Déclenche l'action lorsqu'on pousse sur "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Cloner le repo
        uses: actions/checkout@v3

      - name: 🔧 Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Installer les dépendances
        run: npm install --production

      - name: 🚀 Déployer sur O2Switch via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_TARGET }}
